version: '3'

services:
  web:
    build: ./web
    depends_on:
      - flask # flaskコンテナが起動してから起動
    links:
      - flask # flaskコンテナとリンク
    ports:
      - 3333:80 # http://localhost:3333 => docker://web:80
    volumes:
      - ./app:/var/www/app # アプリケーション開発ディレクトリ
      # nginx設定
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/logs:/etc/nginx/logs
    network_mode: bridge # nginx-proxyにリバースプロキシしてもらうために同一ネットワーク内に置く
    command: nginx -g 'daemon off;' -c /etc/nginx/nginx.conf
    environment:
      TZ: Asia/Tokyo
      # VIRTUAL_HOST設定（nginx-proxy）
      VIRTUAL_HOST: ssl-rpa.localhost # http://ssl-rpa.localhost => docker://web:80
      VIRTUAL_PORT: 80
      # SSL化設定（letsencrypt-nginx-proxy-companion）
      LETSENCRYPT_HOST: ssl-rpa.localhost
      LETSENCRYPT_EMAIL: admin@ssl-rpa.localhost
  
  flask:
    build: ./flask
    volumes:
      - ./app:/var/www/app # アプリケーション開発ディレクトリ
    network_mode: bridge   # nginx-proxyにリバースプロキシしてもらうために同一ネットワーク内に置く
    # uWSGI Emperor を使って複数のFlaskサーバーを起動できるようにする
    command: uwsgi --master --die-on-term --emperor /var/www/app/vassals/*.ini
    environment:
      TZ: Asia/Tokyo
