version: '3'

services:
  web:
    build: ./web
    links:
      - flask # flaskコンテナとリンク
    volumes:
      - ./app:/var/www/app # アプリケーション開発ディレクトリ
      # nginx設定
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/logs:/etc/nginx/logs
    network_mode: bridge # nginx-proxyにリバースプロキシしてもらうために同一ネットワーク内に置く
    command: nginx -g 'daemon off;' -c /etc/nginx/nginx.conf
    environment:
      TZ: Asia/Tokyo
      # VIRTUAL_HOST設定（nginx-proxy）
      VIRTUAL_HOST: ssl-rpa.localhost
      VIRTUAL_PORT: 80
  
  flask:
    build: ./flask
    volumes:
      - ./app:/var/www/app # アプリケーション開発ディレクトリ
    network_mode: bridge   # nginx-proxyにリバースプロキシしてもらうために同一ネットワーク内に置く
    # uWSGI Emperor を使って複数のFlaskサーバーを起動できるようにする
    command: uwsgi --master --die-on-term --emperor /var/www/app/vassals/*.ini
    environment:
      TZ: Asia/Tokyo
